### PR TITLE
bugfix/705: replacing Indexable Types with Map

### LINKED ISSUE #705: Certain wikilink names like [[constructor]] break foam
- Foam version: 0.13.8
- Platform: Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: Yes

**Summary**
Adding a placeholder wiki-link with a special name like [[constructor]], which is a reserved keyword in javascript, breaks foam with an error:
```
An error occurred while bootstrapping Foam. TypeError: this.backlinks[target.path].push is not a function at FoamGraph.connect
``` 

Full traceback (on my computer):

```
An error occurred while bootstrapping Foam. TypeError: this.backlinks[target.path].push is not a function at FoamGraph.connect (/home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:2941:33) at /home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:3000:14 at Array.forEach (<anonymous>) at FoamGraph.resolveResource (/home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:2997:20) at /home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:2845:20 at Array.forEach (<anonymous>) at Function.fromWorkspace (/home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:2844:37) at /home/alex/.vscode/extensions/foam.foam-vscode-0.13.8/node_modules/foam-core/dist/foam-core.cjs.development.js:3663:29
```

**Steps to reproduce**
1. Simply add the placeholder [[constructor]] into any note  
2. Reload vscode

**Additional information**
The same error might happen on other similar keywords, but I cannot confirm it at the moment. This was discovered by accident, and is probably a very special edge case.

### PR DESCRIPTION
**Pull request by JonasSprenger**
Resolve #705

By using an `Indexable Types` like :
```typescript
  public readonly backlinks: { [key: string]: Connection[] } = {};
```
The checks like this don't work if the `key` has the same name as a prototype method
```typescript
this.backlinks[target.path] = this.backlinks[target.path] ?? [];
```
I think the object `this.backlinks` is assign to a function.

One solution is to replace the `Indexable Types` by a `Map`.
After manual checks it work by replacing by a `Map` the two flowing attributes:
  - `public readonly backlinks` of `class FoamGraph`.
  - `private resourcesByName` of `class FoamWorkspace`.
  
I've written a test to catch the bug, but I can't make it work for all the cases.

### CODE REVIEW

**Comment by JonasSprenger** [comment]
_Just for the record_
One hacky solution can be using something like that :
```typescript
    if(!Object.prototype.hasOwnProperty.call(this.backlinks, target.path) || !this.backlinks[target.path]) {
      this.backlinks[target.path] = [];
    }
```

File: packages/foam-core/src/model/graph.ts [hunk 1]
```diff
@@ -27,7 +27,7 @@ export class FoamGraph implements IDisposable {
   /**
    * Maps the connections arriving to a URI
    */
-  public readonly backlinks: { [key: string]: Connection[] } = {};
+  public readonly backlinks: Map<string, Connection[]> = new Map();
```
Comment (riccardoferretti) [inline packages/foam-core/src/model/graph.ts:30]: why was the change limited to `backlinks`, and not `links` and `placeholders`?

**Review by riccardoferretti — COMMENTED** [review]
the direction looks good, I have left a couple of questions

File: packages/foam-core/src/model/graph.ts [hunk 2]
```diff
@@ -194,10 +198,12 @@ export class FoamGraph implements IDisposable {
...
     }
-    this.backlinks[target.path] =
-      this.backlinks[target.path]?.filter(connectionsToKeep) ?? [];
-    if (this.backlinks[target.path].length === 0) {
-      delete this.backlinks[target.path];
+    this.backlinks.set(
+      target.path,
+      this.backlinks.get(target.path)?.filter(connectionsToKeep) ?? []
+    );
+    if ((this.backlinks.get(target.path) as Connection[]).length === 0) {
```
[the remark this answers is not in the document]
Comment (JonasSprenger) [reply packages/foam-core/src/model/graph.ts]: Replace by Optional Chaining : https://github.com/foambubble/foam/pull/729/commits/e458686275f8129aa93d00245d33274b6af2cdf2

File: packages/foam-core/src/model/graph.ts (hunk 1 above)
Comment (JonasSprenger) [reply packages/foam-core/src/model/graph.ts:30]: The goal of the first commit was just to fix the bug.
`backlinks` and  `resourcesByName` are the only ones (Indexable Types) causing this bug.

But I am of the opinion to replace the other ones for consistency.

**Comment by JonasSprenger** [comment]
> hi @JonasSprenger what's the status of this PR?

Hi @riccardoferretti ,
With this last commit https://github.com/foambubble/foam/pull/729/commits/66f0b445f2779f3a2c6243c0a6953b56fbc5f9c9 to replace the other `Indexable Types` it seems good to me.

**Review by riccardoferretti — APPROVED** [review]
This looks good. One thing I would add is a test for the "constructor" bug, to show/prove how the new implementation fixes that problem and keep track of it to avoid future regressions

**Comment by riccardoferretti** [comment]
I noticed the failing test, this is an issue with GH workflow not updating to the latest `foam-core` when running the test on windows, don't worry about it.
Once the tests are in place this is ready to be merged

**Comment by JonasSprenger** [comment]
> This looks good. One thing I would add is a test for the "constructor" bug, to show/prove how the new implementation fixes that problem and keep track of it to avoid future regressions

I added two tests (for a note name and for a placeholder name), I tested it without the fix, it catches the bug as expected https://github.com/foambubble/foam/pull/729/commits/0ad1a027217e9a832818db111f0924a5ffee6a99

**Comment by JonasSprenger** [comment]
#### A question about the contribution process :

Should **I** rebase this branch on `master`, or it will be done (automatically or by you) when merging this PR ?

_I want to avoid overwriting  all commit hashes and braking the links used in the messages when the PR is still open._

Thanks.

**Comment by riccardoferretti** [comment]
it's always best to rebase from master, also to see if other changes might functionally (and not necessarily code-wise) conflict with yours, but if the changeset is uncorrelated a "squash and merge" would still do it.

For this changeset, which is pretty core, I would rebase

**Comment by JonasSprenger** [comment]
@riccardoferretti Sorry for all the delay just for a simple rebase.

There were no conflict and I tested it manually, it works with resources/placeholders named like JS proto properties (e.g. `constructor`, `toLocaleString`)

**Comment by riccardoferretti** [comment]
@allcontributors add @JonasSprenger for code
