### PR TITLE
Only remove link definition token that contain an alias divider

### LINKED ISSUE #696: Non-wikilink link reference definitions do not render links in Markdown Preview
- Foam version: 0.13.8
- Platform: Mac & Linux
- Issue occur on the [foam template](https://github.com/foambubble/foam-template) repo: No (It does not appear the repo contains a non-wikilink link reference definition.)

**Summary**

Non-wikilink link reference definitions are not rendering links in Markdown Preview. Instead of a clickable "link" it displays "[link]".

**Steps to reproduce**

1. Open a new markdown file.
2. Paste the following text.

```
[foo]: /url "title"

[foo]
```

3. Open Markdown Preview.

**Additional information**

- I am using VSCodium 1.57.1.
- Link reference definitions render as clickable links when I install 0.13.7 or disable Foam.

Thanks for looking into this!

### PR DESCRIPTION
**Pull request by pderaaij**
This resolves #696. Where we initially removed the entire reference definition block, we now only remove the one that contain a `|`. So, we allow

`[foo]: /url "title"`

But filter out the following one for the preview:
`[foo|alias]: /url "title"`

### CODE REVIEW

File: packages/foam-vscode/src/features/preview-navigation.ts [hunk 1]
```diff
@@ -96,9 +96,13 @@ export const markdownItWithRemoveLinkReferences = (
   md: markdownit,
   workspace: FoamWorkspace
 ) => {
-  // Forget about reference blocks before processing links.
+  // Forget about reference links that contain an alias divider
   md.inline.ruler.before('link', 'clear-references', state => {
-    state.env.references = undefined;
+    Object.keys(state.env.references).map(refKey => {
```
Comment (riccardoferretti) [inline packages/foam-vscode/src/features/preview-navigation.ts:101]: minor, but let's make linter happy:

```suggestion
    Object.keys(state.env.references).forEach(refKey => {
```

**Review by riccardoferretti — APPROVED** [review]
