### PR TITLE
Daily note could be created before the daily note directory

### LINKED ISSUE #229: First Daily note fails after changing `foam.openDailyNote.directory`
Hi, I'm new. Thank you for all your work so far, foam has been interesting to check out! 

I noticed that immediately after setting `foam.openDailyNote.directory` running the **Open Daily Note** command results in a little error pop-up: 
image
```
Command 'Foam: Open Daily Note' resulted in an error (ENOENT: no such file or directory, open '.../foam/[new directory]/2020-08-23.md')
```

Running the command again works fine as the first invocation created the directory. Looking through the code it seems like the issue might be fixed by adding an `await` here:  
https://github.com/foambubble/foam/blob/d8512db7aa5c8f98e002d0744e54c3312bf50dc1/packages/foam-vscode/src/features/open-daily-note.ts#L66

I am happy to open a pull request if this fix is wanted and if it at least seems like I'm in the right spot to start debugging. 

Thank you!

### PR DESCRIPTION
**Pull request by sksmith**
Fixes #229

### CODE REVIEW

File: packages/foam-vscode/src/features/open-daily-note.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ async function createDailyNoteIfNotExists(
     return false;
   }
 
-  createDailyNoteDirectoryIfNotExists(dailyNotePath);
+  await createDailyNoteDirectoryIfNotExists(dailyNotePath);
```
Comment (ctrlplusb) [inline packages/foam-vscode/src/features/open-daily-note.ts:66]: I think there was an eslint plugin/rule to help with these types of oversights. Such a killer to debug these. Well done for picking it up. 🙏

Comment (ctrlplusb) [reply packages/foam-vscode/src/features/open-daily-note.ts:66]: https://eslint.org/docs/rules/require-await

Comment (sksmith) [reply packages/foam-vscode/src/features/open-daily-note.ts:66]: I went ahead and added the require-await to this pull request. I then cleaned up the warnings for this file specifically. So ya know, require-await wouldn't have found this particular bug because there are already other awaits inside of that function, but it still seems like a handy warning!

File: packages/foam-vscode/src/features/open-daily-note.ts [hunk 2]
```diff
@@ -98,7 +98,7 @@ async function focusDailyNote(dailyNotePath: string, isNewNote: boolean) {
 }
 
 async function pathExists(path: string) {
-  return fs.promises
+  return await fs.promises
```
Comment (anku255) [inline packages/foam-vscode/src/features/open-daily-note.ts:101]: Just curious about the addition of `await` here. Is it required?  https://eslint.org/docs/rules/no-return-await

**Review by anku255 — APPROVED** [review]

File: packages/foam-vscode/src/features/open-daily-note.ts (hunk 2 above)
Comment (jevakallio) [reply packages/foam-vscode/src/features/open-daily-note.ts]: @anku255 thanks for noticing this, I fixed this in [`9a68fe9` (#232)](https://github.com/foambubble/foam/pull/232/commits/9a68fe9f52537fd86eb91ebb5e2dca3751870482)

**Review by jevakallio — APPROVED** [review]
Looks good @sksmith! This change broke link reference definition CodeLens was still using the old API, fixed it in [`52fe704` (#232)](https://github.com/foambubble/foam/pull/232/commits/52fe7041e9212b53758d105000c62dd89accd0ce)

**Comment by jevakallio** [comment]
@all-contributors add @sksmith for code 🎉

**Comment by sksmith** [comment]
Thanks @jevakallio !
